project:
  type: book
  output-dir: docs

number-sections: true

book:
  title: "Fire Physics"
  author: "Michael Försth, LTU"
  
  repo-url: https://github.com/LTU-fire/fp-book/
  repo-subdir: chapters
  repo-branch: main
  repo-actions: [issue]
  url: https://LTU-fire.github.io/fp-book/
  sidebar:
    logo: figures/dragonLogo.png
    search: true
  sharing: [twitter, facebook, linkedin]

  chapters:
    - index.qmd
    - chapters/01_introduction.qmd
    - chapters/02_conduction.qmd
    - chapters/03_radiation.qmd
    - chapters/04_convection.qmd
    - chapters/05_boundary.qmd
    - chapters/06_measurement.qmd
    - chapters/07_numerical.qmd

  
format:
  html:
    theme: cosmo

execute:
  freeze: auto 
